dispatches:
  - title: Demo dispatch config 1
    event_type: todo
    fields:
      - label: Demo Textfield
        name: demo-textfield
        type: text
        validations:
          required: true
          minLength: 10
          pattern: "[0-9]+.[0-9]+.[0-9]+"
      - label: Demo Select
        name: demo-select
        type: select
        items:
          - label: Foo
            value: foo
          - label: Bar
            value: bar
  - title: Demo dispatch config 2
    event_type: todo
    fields:
      - label: Demo Textfield
        name: demo-textfield
        type: text
      - label: Demo Select
        name: demo-select
        type: select
        items:
          - label: Foo
            value: foo
          - label: Bar
            value: bar
